### Advance Numpy
Advance Indexing methods, 
Broadcasting, 
Other Operations

In [1]:
import numpy as np

### Fancy Indexing

In [3]:
# Fancy Indexing
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

- When you don't have pattern to get multiple rows/columns through slicing then you use fancy indexing.

In [4]:
a[[0,1,2]]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [8]:
a[:,[0,2,3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [12]:
a[[0,2,3],0]

array([ 0,  8, 12])

In [13]:
a[[0,3,4],[0,2,1]]

array([ 0, 14, 17])

### Boolean Indexing

In [14]:
a = np.random.randint(1,100,24).reshape(6,4)
a

array([[ 3, 85, 84, 60],
       [61, 83, 45, 54],
       [76, 62, 61, 80],
       [92, 39, 95, 42],
       [47, 24, 76, 73],
       [73, 46, 41, 62]], dtype=int32)

In [15]:
a > 50

array([[False,  True,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True,  True],
       [ True, False,  True, False],
       [False, False,  True,  True],
       [ True, False, False,  True]])

In [16]:
a[a>50]

array([85, 84, 60, 61, 83, 54, 76, 62, 61, 80, 92, 95, 76, 73, 73, 62],
      dtype=int32)

- Here you can see that boolean array is masked on original array and the output is given in 1D form.

In [17]:
a[a%2==0]

array([84, 60, 54, 76, 62, 80, 92, 42, 24, 76, 46, 62], dtype=int32)

In [21]:
a[(a%2==0)&(a>50)] # As we are working with boolean values, we use bitwise operators and not logical.

array([84, 60, 54, 76, 62, 80, 92, 76, 62], dtype=int32)