### More Numpy Functions

In [1]:
import numpy as np

### Sorting Arrays

In [2]:
a = np.random.randint(1,100,15)
b = np.random.randint(1,100,15).reshape(3,5)
print(a,'\n\n', b)

[11 78 43 19 96 50 21  1 83 19 46 37 50 76 28] 

 [[40  5 73 16 99]
 [62 78 75 25  8]
 [49 92 48  9 21]]


In [3]:
np.sort(a)

array([ 1, 11, 19, 19, 21, 28, 37, 43, 46, 50, 50, 76, 78, 83, 96],
      dtype=int32)

In [4]:
np.sort(b) # By default row-wise sorting

array([[ 5, 16, 40, 73, 99],
       [ 8, 25, 62, 75, 78],
       [ 9, 21, 48, 49, 92]], dtype=int32)

In [5]:
np.sort(b, axis=0) # Column-wise sorting

array([[40,  5, 48,  9,  8],
       [49, 78, 73, 16, 21],
       [62, 92, 75, 25, 99]], dtype=int32)

In [6]:
np.sort(a)[::-1] # Descending sorting

array([96, 83, 78, 76, 50, 50, 46, 43, 37, 28, 21, 19, 19, 11,  1],
      dtype=int32)

In [7]:
np.sort(b, kind='mergesort')

array([[ 5, 16, 40, 73, 99],
       [ 8, 25, 62, 75, 78],
       [ 9, 21, 48, 49, 92]], dtype=int32)

### Some other basic functions

In [8]:
a

array([11, 78, 43, 19, 96, 50, 21,  1, 83, 19, 46, 37, 50, 76, 28],
      dtype=int32)

In [9]:
# Append
np.append(a,200)

array([ 11,  78,  43,  19,  96,  50,  21,   1,  83,  19,  46,  37,  50,
        76,  28, 200])

In [10]:
b

array([[40,  5, 73, 16, 99],
       [62, 78, 75, 25,  8],
       [49, 92, 48,  9, 21]], dtype=int32)

In [11]:
np.append(b, np.ones((b.shape[0], 1)), axis=1)

array([[40.,  5., 73., 16., 99.,  1.],
       [62., 78., 75., 25.,  8.,  1.],
       [49., 92., 48.,  9., 21.,  1.]])

In [12]:
# Concatenate
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)

print(a)
print()
print(b)

[[0 1 2]
 [3 4 5]]

[[ 6  7  8]
 [ 9 10 11]]


In [13]:
np.concatenate((a,b)) # Similar to vstack

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [14]:
np.concatenate((a,b), axis=1) # Similar to hstack

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [15]:
# Unique
e = np.array([1,1,1,2,2,3,4,5,5,5,6])
np.unique(e)

array([1, 2, 3, 4, 5, 6])

In [16]:
# Expand dims
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
np.expand_dims(a,axis=0) # Makes row vector

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [21]:
np.expand_dims(a,axis=1) # Makes column vector

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [22]:
# Where
a = np.random.randint(1,100,10)
a

array([20,  8, 36, 58, 59, 27, 96, 84, 27,  6], dtype=int32)

In [25]:
np.where(a>50) # Gives index acc. to condition

(array([3, 4, 6, 7]),)

In [26]:
np.where(a>50,-1,a) # np.where(condition, true, false)

array([20,  8, 36, -1, -1, 27, -1, -1, 27,  6], dtype=int32)

In [38]:
# Argmax
np.argmax(a) # Index of largest item

np.int64(6)

In [29]:
b

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [33]:
np.argmax(b) # Element-wise

np.int64(5)

In [34]:
np.argmax(b,axis=0) # Column-wise

array([1, 1, 1])

In [37]:
# Argmin
print(a)
np.argmin(a) # Index of smallest item

[20  8 36 58 59 27 96 84 27  6]


np.int64(9)

In [42]:
# Cumsum
print(a)
np.cumsum(a) # Array of cumulative sum

[20  8 36 58 59 27 96 84 27  6]


array([ 20,  28,  64, 122, 181, 208, 304, 388, 415, 421])

In [48]:
print(b)
np.cumsum(b) # Element-wise

[[ 6  7  8]
 [ 9 10 11]]


array([ 6, 13, 21, 30, 40, 51])

In [47]:
np.cumsum(b,axis=0) # Column-wise

array([[ 6,  7,  8],
       [15, 17, 19]])

In [49]:
# Cumprod
np.cumprod(a) # Cumulative product

array([             20,             160,            5760,          334080,
              19710720,       532189440,     51090186240,   4291575644160,
       115872542392320, 695235254353920])

In [51]:
# Percentile
print(a)
np.percentile(a,100)

[20  8 36 58 59 27 96 84 27  6]


np.float64(96.0)

In [52]:
np.percentile(a,0)

np.float64(6.0)

In [53]:
np.percentile(a,65)

np.float64(54.70000000000001)

In [54]:
np.percentile(a,75)

np.float64(58.75)

In [57]:
# Histogram
print(a)
np.histogram(a,bins=np.arange(0,101,10)) # Gives frequency count acc. to bins

[20  8 36 58 59 27 96 84 27  6]


(array([2, 0, 3, 1, 0, 2, 0, 0, 1, 1]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [59]:
# Corrcoef
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience) # Gives correlation coefficient between quantities

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])