### More Numpy Functions

In [1]:
import numpy as np

### Sorting Arrays

In [2]:
a = np.random.randint(1,100,15)
b = np.random.randint(1,100,15).reshape(3,5)
print(a,'\n\n', b)

[79 75 86 25  4 13  2  3 99 33 52 38 81 93 40] 

 [[23 67 80 89 85]
 [62 51 53 97 74]
 [ 2 29 34 99 73]]


In [3]:
np.sort(a)

array([ 2,  3,  4, 13, 25, 33, 38, 40, 52, 75, 79, 81, 86, 93, 99],
      dtype=int32)

In [ ]:
np.sort(b) # By default row-wise sorting

array([[23, 67, 80, 85, 89],
       [51, 53, 62, 74, 97],
       [ 2, 29, 34, 73, 99]], dtype=int32)

In [ ]:
np.sort(b, axis=0) # Column-wise sorting

array([[ 2, 29, 34, 89, 73],
       [23, 51, 53, 97, 74],
       [62, 67, 80, 99, 85]], dtype=int32)

In [7]:
np.sort(a)[::-1] # Descending sorting

array([99, 93, 86, 81, 79, 75, 52, 40, 38, 33, 25, 13,  4,  3,  2],
      dtype=int32)

In [8]:
np.sort(b, kind='mergesort')

array([[23, 67, 80, 85, 89],
       [51, 53, 62, 74, 97],
       [ 2, 29, 34, 73, 99]], dtype=int32)

### Some other basic functions

In [9]:
a

array([79, 75, 86, 25,  4, 13,  2,  3, 99, 33, 52, 38, 81, 93, 40],
      dtype=int32)

In [11]:
# Append
np.append(a,200)

array([ 79,  75,  86,  25,   4,  13,   2,   3,  99,  33,  52,  38,  81,
        93,  40, 200])

In [12]:
b

array([[23, 67, 80, 89, 85],
       [62, 51, 53, 97, 74],
       [ 2, 29, 34, 99, 73]], dtype=int32)

In [16]:
np.append(b, np.ones((b.shape[0], 1)), axis=1)

array([[23., 67., 80., 89., 85.,  1.],
       [62., 51., 53., 97., 74.,  1.],
       [ 2., 29., 34., 99., 73.,  1.]])

In [19]:
# Concatenate
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)

print(a)
print()
print(b)

[[0 1 2]
 [3 4 5]]

[[ 6  7  8]
 [ 9 10 11]]


In [22]:
np.concatenate((a,b)) # Similar to vstack

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [23]:
np.concatenate((a,b), axis=1) # Similar to hstack

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [25]:
# Unique
e = np.array([1,1,1,2,2,3,4,5,5,5,6])
np.unique(e)

array([1, 2, 3, 4, 5, 6])